/**
 * Reusable demo bundled-anchor calibration — converts PDF auto-setup geometry
 * (or hand-supplied system/barline tables) into the demo anchors JSON format.
 *
 * Tooling only; does not change runtime score-follow behaviour.
 */
import { allocateSpansByCounts } from './allocateMeasuresToSystems.js'
import { buildPerMeasureSystemAnchors } from './semiAutoScoreAlignment.js'
import { ANCHOR_SOURCE } from './anchorUtils.js'
import {
  ANCHOR_COMPARISON_FIELDS,
  ANCHOR_PROMOTION_TOLERANCES,
  assessPromotionReadiness,
  compareAnchorSets,
  formatAnchorComparisonText,
  PROMOTION_STATUS,
} from './anchorComparison.js'

export const CALIBRATION_SOURCE = {
  AUTO: 'auto-pipeline',
  MANUAL: 'manual-systems',
  HYBRID: 'auto+manual-overrides',
}

/** Tolerances for --validate-minuet (geometry must match hand-calibrated reference). */
export const DEMO_CALIBRATION_VALIDATE_TOLERANCES = ANCHOR_PROMOTION_TOLERANCES.ready

function getWrittenMeasureNumbers(timingMap) {
  if (!timingMap?.measures?.length) {
    return []
  }
  return timingMap.measures.map((measure) => measure.number)
}

/**
 * Build bundled demo anchors from the manual system table used by
 * `generate-demo-anchors.mjs` (PyMuPDF-style measure x positions).
 *
 * @param {Array<{ systemIndex, y, endX, measures: Array<{ n, x }> }>} systems
 */
export function buildBundledAnchorsFromManualSystems(systems, meta = {}) {
  const anchors = []
  for (const sys of systems) {
    for (let index = 0; index < sys.measures.length; index += 1) {
      const { n, x } = sys.measures[index]
      const nextMeasure = sys.measures[index + 1]
      const playableEndX = nextMeasure?.x ?? sys.endX
      anchors.push(makeBundledMeasureAnchor({
        page: sys.page ?? 1,
        y: sys.y,
        measureNumber: n,
        systemIndex: sys.systemIndex,
        measureStartX: x,
        playableStartX: x,
        playableEndX,
        systemEndX: sys.endX,
        calibrated: meta.calibrated ?? CALIBRATION_SOURCE.MANUAL,
        xSource: 'manual-table',
      }))
    }
  }
  return wrapBundledPayload(anchors, meta)
}

/** Convert auto-setup supplemental measure anchors into bundled demo shape. */
export function buildBundledAnchorsFromAutoAnchors(supplementalAnchors, meta = {}) {
  const anchors = (supplementalAnchors ?? []).map((anchor) => {
    const m = anchor.meta ?? {}
    const measureStartX = Number.isFinite(m.measureStartX) ? m.measureStartX : anchor.x
    const playableStartX = Number.isFinite(m.playableStartX) ? m.playableStartX : anchor.x
    return makeBundledMeasureAnchor({
      page: anchor.page,
      y: anchor.y,
      measureNumber: anchor.measureNumber,
      systemIndex: m.systemIndex ?? 0,
      measureStartX,
      playableStartX,
      playableEndX: m.playableEndX,
      systemEndX: m.systemEndX,
      calibrated: meta.calibrated ?? CALIBRATION_SOURCE.AUTO,
      xSource: m.xSource ?? 'auto-pipeline',
      confidence: m.confidence,
    })
  })
  return wrapBundledPayload(anchors, meta)
}

function makeBundledMeasureAnchor({
  page,
  y,
  measureNumber,
  systemIndex,
  measureStartX,
  playableStartX,
  playableEndX,
  systemEndX,
  calibrated,
  xSource,
  confidence = null,
}) {
  return {
    page,
    // Cursor start-lock and exact holds use anchor.x — must be the first playable
    // beat, not the left barline / clef margin.
    x: playableStartX,
    y,
    measureNumber,
    source: ANCHOR_SOURCE.DEMO,
    meta: {
      role: 'measure',
      density: 'pdf-extracted',
      systemIndex,
      calibrated,
      bundled: true,
      measureStartX,
      playableStartX,
      playableEndX,
      systemEndX,
      ...(xSource ? { xSource } : {}),
      ...(Number.isFinite(confidence) ? { confidence } : {}),
    },
  }
}

function wrapBundledPayload(anchors, meta) {
  return {
    version: 1,
    pieceId: meta.pieceId ?? 'demo-piece',
    pdfFile: meta.pdfFile ?? 'score.pdf',
    timingFile: meta.timingFile ?? 'score.musicxml',
    generatedAt: meta.generatedAt ?? new Date().toISOString(),
    alignmentNote:
      meta.alignmentNote ??
      'Bundled demo anchors generated by demo anchor calibration tooling. ' +
        'Loaded only for the sample piece; never saved to user localStorage.',
    calibration: {
      source: meta.calibrated ?? CALIBRATION_SOURCE.AUTO,
      warnings: meta.warnings ?? [],
    },
    anchors: anchors.sort((a, b) => a.measureNumber - b.measureNumber),
  }
}

/**
 * Run measure allocation + per-measure anchor build from detected systems.
 * Supports forced per-system measure counts and optional manual barline overrides.
 */
export function calibrateAnchorsFromDetection({
  systemEntries,
  timingMap,
  forcedMeasureCounts = null,
  manualBarlinesBySystem = null,
}) {
  const measureNumbers = getWrittenMeasureNumbers(timingMap)
  const warnings = []

  if (!systemEntries?.length) {
    return { ok: false, warnings: ['No staff systems detected in PDF.'], supplemental: [] }
  }

  let measureCounts = forcedMeasureCounts
  let allocationMode = 'forced-counts'

  if (!measureCounts) {
    measureCounts = systemEntries.map((entry) => entry.system?.measureEstimate ?? null)
    const haveAll = measureCounts.every((c) => Number.isFinite(c) && c >= 1)
    const total = haveAll ? measureCounts.reduce((a, b) => a + b, 0) : 0
    const countsUsable =
      haveAll &&
      measureNumbers.length > 0 &&
      Math.abs(total - measureNumbers.length) <= Math.max(2, measureNumbers.length * 0.25)

    if (!countsUsable) {
      warnings.push(
        'Automatic barline measure counts unavailable or mismatched score — ' +
          'pass --counts or manual barlines for reliable calibration.',
      )
      allocationMode = 'unusable-auto-counts'
      return { ok: false, warnings, supplemental: [], allocationMode }
    }
    allocationMode = 'barline-counts'
  } else if (measureCounts.reduce((a, b) => a + b, 0) !== measureNumbers.length) {
    warnings.push(
      `Forced measure counts sum to ${measureCounts.reduce((a, b) => a + b, 0)} ` +
        `but score has ${measureNumbers.length} measures.`,
    )
    return {
      ok: false,
      warnings,
      supplemental: [],
      measureCounts,
      allocationMode: 'forced-count-mismatch',
    }
  }

  if (systemEntries.length !== measureCounts.length) {
    warnings.push(
      `Detected ${systemEntries.length} systems but ${measureCounts.length} measure-count entries.`,
    )
  }

  for (const entry of systemEntries) {
    const sys = entry.system
    if (sys?.barlineConfident === false) {
      warnings.push(
        `System p${entry.page} y≈${sys.center?.toFixed(3) ?? '?'}: unreliable barline count ` +
          `(${sys.barlineReliabilityReason ?? 'unknown'}).`,
      )
    }
  }

  const spans = allocateSpansByCounts(systemEntries, measureNumbers, measureCounts)
  let supplemental = buildPerMeasureSystemAnchors(systemEntries, spans, timingMap)

  if (manualBarlinesBySystem) {
    supplemental = applyManualBarlineOverrides(
      supplemental,
      manualBarlinesBySystem,
      systemEntries,
      spans,
      warnings,
    )
    allocationMode = `${allocationMode}+manual-barlines`
  }

  return {
    ok: supplemental.length === measureNumbers.length,
    supplemental,
    spans,
    measureCounts,
    allocationMode,
    warnings,
  }
}

function applyManualBarlineOverrides(anchors, manualBarlinesBySystem, systemEntries, spans, warnings) {
  const byMeasure = new Map(anchors.map((a) => [a.measureNumber, { ...a, meta: { ...a.meta } }]))

  spans.forEach((span, systemIndex) => {
    const override = manualBarlinesBySystem[systemIndex] ?? manualBarlinesBySystem[String(systemIndex)]
    const barlineXs = override?.barlineXs ?? override
    if (!Array.isArray(barlineXs) || barlineXs.length < 2) {
      return
    }
    const numbers = span.measureNumbers ?? []
    if (barlineXs.length !== numbers.length + 1) {
      warnings.push(
        `System ${systemIndex}: manual barlines length ${barlineXs.length} ` +
          `≠ ${numbers.length + 1} (measures + 1). Skipping override.`,
      )
      return
    }
    const entry = systemEntries[systemIndex]
    const y = anchors.find((a) => a.meta?.systemIndex === systemIndex)?.y ?? entry?.system?.center
    const systemEndX = barlineXs[barlineXs.length - 1]

    numbers.forEach((measureNumber, i) => {
      const measureStartX = barlineXs[i]
      const playableEndX = barlineXs[i + 1]
      const prev = byMeasure.get(measureNumber)
      byMeasure.set(measureNumber, {
        ...(prev ?? {
          page: entry?.page ?? 1,
          y,
          measureNumber,
          source: ANCHOR_SOURCE.AUTO_MEASURE,
        }),
        x: measureStartX,
        meta: {
          ...(prev?.meta ?? {}),
          role: 'measure',
          systemIndex,
          measureStartX,
          playableStartX: measureStartX,
          playableEndX,
          systemEndX,
          xSource: 'manual-barlines',
        },
      })
    })
  })

  return [...byMeasure.values()].sort((a, b) => a.measureNumber - b.measureNumber)
}

/** Reverse bundled anchors into manual system tables (for round-trip tests). */
export function manualSystemsFromBundledPayload(payload) {
  const bySystem = new Map()
  for (const anchor of payload.anchors ?? []) {
    const systemIndex = anchor.meta?.systemIndex ?? 0
    if (!bySystem.has(systemIndex)) {
      bySystem.set(systemIndex, {
        systemIndex,
        page: anchor.page ?? 1,
        y: anchor.y,
        endX: anchor.meta?.systemEndX ?? anchor.x,
        measures: [],
      })
    }
    const sys = bySystem.get(systemIndex)
    sys.measures.push({
      n: anchor.measureNumber,
      x: anchor.meta?.measureStartX ?? anchor.x,
    })
    sys.y = anchor.y
    sys.endX = anchor.meta?.systemEndX ?? sys.endX
  }
  return [...bySystem.values()]
    .sort((a, b) => a.systemIndex - b.systemIndex)
    .map((sys) => ({
      ...sys,
      measures: sys.measures.sort((a, b) => a.n - b.n),
    }))
}

/** Validate that bundled measure anchors place the cursor in playable content, not margins. */
export function assessBundledMeasureCursorX(anchor) {
  if (anchor?.meta?.role !== 'measure') {
    return { ok: true }
  }

  const x = anchor.x
  const measureStartX = anchor.meta?.measureStartX
  const playableStartX = anchor.meta?.playableStartX

  if (Number.isFinite(playableStartX) && x < playableStartX - 0.01) {
    return { ok: false, reason: 'cursor-before-playable-start' }
  }

  // Reject hybrid bundles that park x on the left barline when beat-1 metadata
  // sits past the clef/key area (Hungarian Dance regression).
  if (
    anchor.measureNumber === 1 &&
    Number.isFinite(measureStartX) &&
    Number.isFinite(playableStartX) &&
    playableStartX - measureStartX > 0.05 &&
    x < measureStartX + 0.02
  ) {
    return { ok: false, reason: 'measure-1-on-clef-margin' }
  }

  return { ok: true }
}

/** Validate a bundled payload (piece-agnostic; optional measure-1 guard). */
export function validateBundledAnchorPayload(payload, options = {}) {
  const {
    pieceId = null,
    requireMeasureOneOnPage1 = true,
    maxMeasureOneY = 0.38,
  } = options

  if (!payload || !Array.isArray(payload.anchors)) {
    return { ok: false, reason: 'missing-anchors' }
  }
  if (pieceId && payload.pieceId !== pieceId) {
    return { ok: false, reason: 'piece-mismatch' }
  }

  const anchors = payload.anchors.filter(
    (a) =>
      Number.isFinite(a.measureNumber) &&
      Number.isFinite(a.page) &&
      Number.isFinite(a.x) &&
      Number.isFinite(a.y),
  )
  if (anchors.length < 2) {
    return { ok: false, reason: 'too-few-anchors' }
  }

  const measureNumbers = anchors.map((a) => a.measureNumber)
  if (new Set(measureNumbers).size !== measureNumbers.length) {
    return { ok: false, reason: 'duplicate-measure-anchors' }
  }

  const measureOne = anchors.find((a) => a.measureNumber === 1)
  if (!measureOne) {
    return { ok: false, reason: 'missing-measure-1' }
  }
  if (requireMeasureOneOnPage1 && (measureOne.page !== 1 || measureOne.y > maxMeasureOneY)) {
    return { ok: false, reason: 'measure-1-not-on-system-1' }
  }

  const measureOneCursor = assessBundledMeasureCursorX(measureOne)
  if (!measureOneCursor.ok) {
    return measureOneCursor
  }

  for (const anchor of anchors) {
    const cursor = assessBundledMeasureCursorX(anchor)
    if (!cursor.ok) {
      return cursor
    }
  }

  return { ok: true, anchors, warnings: payload.calibration?.warnings ?? [] }
}

/** Compare generated bundled anchors to a trusted reference; return promotion readiness. */
export function compareBundledAnchorsToReference(generatedPayload, referencePayload, options = {}) {
  const fields = options.fields ?? ANCHOR_COMPARISON_FIELDS
  const comparison = compareAnchorSets(generatedPayload.anchors, referencePayload.anchors, { fields })
  const readiness = assessPromotionReadiness(comparison, options.tolerances ?? DEMO_CALIBRATION_VALIDATE_TOLERANCES)
  return { comparison, readiness, reportText: formatAnchorComparisonText(comparison, readiness) }
}

export function formatCalibrationSummary(payload, { comparison, readiness, warnings = [] } = {}) {
  const lines = [
    `pieceId: ${payload.pieceId}`,
    `anchors: ${payload.anchors?.length ?? 0}`,
    `source: ${payload.calibration?.source ?? 'unknown'}`,
  ]
  if (warnings.length) {
    lines.push(`warnings (${warnings.length}):`)
    warnings.forEach((w) => lines.push(`  - ${w}`))
  }
  if (comparison) {
    lines.push(
      `comparison: max err ${comparison.maxError.toFixed(4)} | avg err ${comparison.avgError.toFixed(4)}`,
    )
    lines.push(`readiness: ${readiness?.status ?? 'unknown'}`)
  }
  return lines.join('\n')
}

export { PROMOTION_STATUS }
